insert into country(name, phone_code) values('United States of America','+1');
insert into country(name, phone_code) values('Afghanistan','+93');
insert into country(name, phone_code) values('Albania','+355');
insert into country(name, phone_code) values('Algeria','+213');
insert into country(name, phone_code) values('American Samoa','+1-684');
insert into country(name, phone_code) values('Andorra','+376');
insert into country(name, phone_code) values('Angola','+244');
insert into country(name, phone_code) values('Anguilla','+1-264');
insert into country(name, phone_code) values('Antarctica','+672');
insert into country(name, phone_code) values('Argentina','+54');
insert into country(name, phone_code) values('Armenia','+374');
insert into country(name, phone_code) values('Ascension','+247');
insert into country(name, phone_code) values('Australia','+61');
insert into country(name, phone_code) values('Australian External Territories','+672');
insert into country(name, phone_code) values('Austria','+43');
insert into country(name, phone_code) values('Azerbaijan','+994');
insert into country(name, phone_code) values('Bahamas','+1-242');
insert into country(name, phone_code) values('Bahrain','+973');
insert into country(name, phone_code) values('Bangladesh','+880');
insert into country(name, phone_code) values('Barbados','+1-246');
insert into country(name, phone_code) values('Barbuda','+1-268');
insert into country(name, phone_code) values('Belarus','+375');
insert into country(name, phone_code) values('Belgium','+32');
insert into country(name, phone_code) values('Belize','+501');
insert into country(name, phone_code) values('Benin','+229');
insert into country(name, phone_code) values('Bermuda','+1-441');
insert into country(name, phone_code) values('Bhutan','+975');
insert into country(name, phone_code) values('Bolivia','+591');
insert into country(name, phone_code) values('Bosnia & Herzegovina','+387');
insert into country(name, phone_code) values('Botswana','+267');
insert into country(name, phone_code) values('Brazil','+55');
insert into country(name, phone_code) values('British Virgin Islands','+1-284');
insert into country(name, phone_code) values('Brunei Darussalam','+673');
insert into country(name, phone_code) values('Burkina Faso','+226');
insert into country(name, phone_code) values('Burundi','+257');
