server:
  port: 8089
spring:
  application:
    name: paises
  profiles:
    active: default
  zipkin:
    base-url: http://localhost:9411
#  config:
#    import: "optional:configserver:http://localhost:8888"

  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true